kind: pipeline
name: default

workspace:
   base: /go
   path: src/github.com/fanux/fist/

steps:
- name: build-fist
  image: golang:1.10.8
  commands:
     - go get -v
     - go build -o fist

- name: publish-fist
  image: plugins/docker
  settings:
    repo: fanux/fist
    tags: ${DRONE_TAG=latest}
    username: fanux
    dockerfile: deploy/Dockerfile
    password:
      from_secret: docker-hub-pass
 

   #steps:
   #- name: build-auth
   #  image: golang:1.10.8
   #  commands:
   #     - cd auth && go build -o auth
   #
   #- name: publish-auth
   #  image: plugins/docker
   #  settings:
   #    repo: fanux/fist-auth
   #    tags: ${DRONE_TAG=latest}
   #    username: fanux
   #    dockerfile: auth/deploy/Dockerfile
   #    password:
   #      from_secret: docker-hub-pass
   #
   #- name: build-terminal
   #  image: golang:1.10.8
   #  commands:
   #     - cd terminal && go get && go build -o terminal
   #
   #- name: publish-terminal
   #  image: plugins/docker
   #  settings:
   #    repo: fanux/fist-terminal
   #    tags: ${DRONE_TAG=latest}
   #    username: fanux
   #    dockerfile: terminal/deploy/Dockerfile
   #    password:
   #      from_secret: docker-hub-pass
