apiVersion: v1
kind: Namespace
metadata:
  name: sealyun
---
apiVersion: apps/v1
metadata:
  name: fist
  namespace: sealyun
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fist
  template:
    metadata:
      labels:
        name: fist
    spec:
      containers:
      - name: fist
        image: fanux/fist:latest
        imagePullPolicy: Always
        command: ["start.sh"]
        ports:
        - containerPort: 8080
#       resources:
#         limits:
#           memory: "128Mi"
#           cpu: "1000m"
#         requests:
#           memory: "128Mi"
#           cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: fist
  namespace: sealyun
spec:
  type: ClusterIP
  ports:
  - name: fist
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: fist
